config/routes.rb
Spree::Core::Engine.routes.draw do
  get '/authorizenet_iframe_communicator', to: 'authorizenet_hosted_form#iframe',
                                           as: :authorizenet_iframe_communicator
  post '/authorizenet_form_callback/addPayment', to: 'authorizenet_hosted_form#add_payment',
                                                 as: :authorizenet_hosted_form_add_payment_callback
end

app/models/active_merchant/billing/authorize_net_cim_decorator.rb
require 'active_merchant/billing/gateways/authorize_net_cim'

# This is _really_ bad form, updating a constant like this.
#
# Keep an eye on this as you upgrade ActiveMerchant.
ActiveMerchant::Billing::AuthorizeNetCimGateway::CIM_ACTIONS[:get_hosted_profile_page] = 'getHostedProfilePage'

ActiveMerchant::Billing::AuthorizeNetCimGateway.class_eval do
  class_attribute :test_hosted_form_url, :live_hosted_form_url

  self.test_hosted_form_url = 'https://test.authorize.net/customer'
  self.live_hosted_form_url = 'https://accept.authorize.net/customer'

  # Retrieve a hosted form token for a given customer.
  #
  # Returns a Response whose params hash contains a hosted form token.
  #
  # ==== Options
  #
  # * <tt>:customer_profile_id</tt> -- The Customer Profile ID of the customer. (REQUIRED)
  def get_hosted_profile_page(options = {})
    requires!(options, :customer_profile_id)

    request = build_request(:get_hosted_profile_page, options)
    commit(:get_hosted_profile_page, request)
  end

  def build_get_hosted_profile_page_request(xml, options = {})
    xml.tag!('customerProfileId', options[:customer_profile_id])
    xml.tag!('hostedProfileSettings') do |settings|
      add_authorizenet_hosted_profile_setting(settings, 'hostedProfileValidationMode', test? ? 'testMode' : 'liveMode')

      {
        return_url: 'hostedProfileReturnUrl',
        return_url_text: 'hostedProfileReturnUrlText',
        page_border_visible: 'hostedProfilePageBorderVisible',
        heading_bg_color: 'hostedProfileHeadingBgColor',
        iframe_communicator_url: 'hostedProfileIFrameCommunicatorUrl',
        billing_address_required: 'hostedProfileBillingAddressRequired',
        card_code_required: 'hostedProfileCardCodeRequired'
      }.each_pair do |param, tag|
        next unless options[param]
        add_authorizenet_hosted_profile_setting(settings, tag, options[param])
      end
    end

    xml.target!
  end

  def get_hosted_profile_url(action)
    url = test? ? test_hosted_form_url : live_hosted_form_url
    "#{url}/#{action.to_s.camelize(:lower)}"
  end

  private

  def add_authorizenet_hosted_profile_setting(settings_xml, name, value)
    settings_xml.tag!('setting') do |setting|
      setting.settingName(name)
      setting.settingValue(value)
    end
    settings_xml
  end
end

app/models/spree/address_decorator.rb
Spree::Address.class_eval do
  def require_phone?
    false
  end
end

app/models/spree/gateway/authorizenet_cim_decorator.rb
Spree::Gateway::AuthorizeNetCim.class_eval do
  def get_hosted_form_token_for_order(order, params = {})
    profile_id = create_customer_profile_from_order(order)
    get_hosted_form_token(profile_id, params)
  end

  def create_customer_profile_from_order(order)
    response = cim_gateway.create_customer_profile(
      profile: {
        merchant_customer_id: "#{Time.now.to_f}",
        email: order.user.try(:email)
      },
      validation_mode: :none
    )

    if response.success?
      response.params['customer_profile_id']
    else
      raise ::Spree::Core::GatewayError.new(response.message)
    end
  end

  def get_hosted_form_token(profile_id, params = {})
    response = cim_gateway.get_hosted_profile_page(params.merge(customer_profile_id: profile_id))

    if response.success?
      response.params['token']
    else
      raise ::Spree::Core::GatewayError.new(response.message)
    end
  end

  def get_hosted_form_url(action)
    cim_gateway.get_hosted_profile_url(action)
  end

  def create_payment_methods_from_customer_profile(profile_id, user)
    response = cim_gateway.get_customer_profile(customer_profile_id: profile_id)
    raise ::Spree::Core::GatewayError.new(response.message) unless response.success?

    Array.wrap(response.params['profile']['payment_profiles']).each do |profile|
      case
      when profile['payment'].key?('credit_card')
        create_credit_card_from_customer_payment_profile(profile, profile_id, user)
      when profile['payment'].key?('bank_account')
        create_bank_account_from_customer_payment_profile(profile, profile_id, user)
      else
        raise 'Unknown payment method type'
      end
    end
  end

  private

  def create_credit_card_from_customer_payment_profile(profile, customer_profile_id, user)
    address = create_address_from_customer_payment_profile(profile)

    now = Time.now.utc
    Spree::CreditCard.create!(
      # We need to make a bogus expiration date here since authorize.net does
      # not return the real expiration date in its response.
      month: now.month, year: now.year + 2,

      cc_type: profile['payment']['credit_card']['card_type'].downcase.underscore.gsub(' ', '_'),
      last_digits: profile['payment']['credit_card']['card_number'].last(4),
      address_id: address.id,
      gateway_customer_profile_id: customer_profile_id,
      gateway_payment_profile_id: profile['customer_payment_profile_id'],
      name: "#{profile['bill_to']['first_name']} #{profile['bill_to']['last_name']}",
      user_id: user.id,
      payment_method_id: id
    )
  end

  # This is a stub method to handle bank accounts.
  #
  # If your store supports bank accounts as a payment method, override this
  # method and save the bank account in your system.
  #
  # - profile: A hash of the payment profile from Authorize.net
  # - customer_profile_id: The profile ID of the current customer
  # - user: The currently-logged-in user
  def create_bank_account_from_customer_payment_profile(profile, customer_profile_id, user)
    raise BankAccountsNotAccepted.new
  end \
    unless method_defined?(:create_bank_account_from_customer_payment_profile) || \
      private_method_defined?(:create_bank_account_from_customer_payment_profile)

  def create_address_from_customer_payment_profile(profile)
    Spree::Address.new(
      firstname: profile['bill_to']['first_name'],
      lastname: profile['bill_to']['last_name'],
      address1: profile['bill_to']['address'],
      city: profile['bill_to']['city'],
      zipcode: profile['bill_to']['zip'],
      phone: profile['bill_to']['phone_number'],
      company: profile['bill_to']['company'],
      state_name: profile['bill_to']['state']
    ).tap do |address|
      address.country = Spree::Country.find_by_name(profile['bill_to']['country']) || Spree::Country.default
      address.state = address.country.states.find_all_by_name_or_abbr(profile['bill_to']['state']).first
      address.save!
    end
  end

  class BankAccountsNotAccepted < RuntimeError
    def initialize; end

    def message
      Spree.t('authorizenet_hosted_cim.bank_accounts_not_accepted')
    end
  end
end

app/models/spree/order_decorator.rb
Spree::Order.class_eval do
  # Redefine the checkout flow to place the `payment` step before the `address`
  # step, since the user is required to enter their billing address on
  # Authorize.net's hosted form.
  checkout_flow do
    go_to_state :payment, if: ->(order) { order.payment_required? }
    go_to_state :address
    go_to_state :delivery
    go_to_state :confirm, if: ->(order) { order.confirmation_required? }
    go_to_state :complete
  end

  state_machine.after_transition from: :delivery, do: :update_payment_total_with_shipping

  private

  def update_payment_total_with_shipping
    payment = payments.valid.first
    return unless payment && payment.amount != total
    payment.update!(amount: total)
  end

  # Overridden to grab the default billing/shipping addresses from the payment
  # method entered previously.
  def assign_default_addresses!
    if payments.any?
      clone_billing_from_payments
      clone_shipping_from_payments if checkout_steps.include?("delivery")
    elsif user
      clone_billing
      clone_shipping if checkout_steps.include?("delivery")
    end
  end

  def clone_billing_from_payments
    return if bill_address_id
    address = address_from_payments
    self.bill_address = address.try(:clone) if address.try(:valid?)
  end

  def clone_shipping_from_payments
    return if ship_address_id
    address = address_from_payments
    self.ship_address = address.try(:clone) if address.try(:valid?)
  end

  def address_from_payments
    payment = payments.find { |p| p.source.present? && p.source.address_id.present? }
    Spree::Address.find(payment.source.address_id) if payment && payment.source.address_id
  end
end

app/views/spree/authorizenet_hosted_form/iframe.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>IFrame Communicator</title>
    <script type="text/javascript">
    //<![CDATA[

    (function(window) {
      function mainPage() {
        if (window && window.parent && window.parent.parent) {
          return window.parent.parent;
        }
      }

      var eventHandler = function(event) {
        return mainPage().AuthorizenetHostedForm.handleEvent(event);
      }

      if (window.addEventListener) {
        window.addEventListener("message", eventHandler, false);
      } else if (window.attachEvent) {
        window.attachEvent("onmessage", eventHandler);
      }
    })(window);

    //]]>
    </script>
  </head>
  <body></body>
</html>

app/views/spree/checkout/_address.html.erb
<div class="row">
  <div class="col-sm-6" data-hook="billing_fieldset_wrapper">
    <div class="panel panel-default" id="billing" data-hook>
      <%= form.fields_for :bill_address do |bill_form| %>
        <div class="panel-heading">
          <h3 class="panel-title"><%= Spree.t(:billing_address) %></h3>
        </div>
        <div class="panel-body">
            <%= render :partial => 'spree/address/form', :locals => { :form => bill_form, :address_type => 'billing', :address => @order.bill_address } %>
        </div>
      <% end %>
    </div>
  </div>

  <div class="col-sm-6" data-hook="shipping_fieldset_wrapper">
    <div class="panel panel-default" id="shipping" data-hook>
      <%= form.fields_for :ship_address do |ship_form| %>
        <div class="panel-heading">
          <h3 class="panel-title"><%= Spree.t(:shipping_address) %></h3>
        </div>
        <div class="panel-body">
          <p class="field checkbox" data-hook="use_billing">
            <%= label_tag :order_use_billing, :id => 'use_billing' do %>
              <%= check_box_tag 'order[use_billing]', '1', @order.shipping_eq_billing_address? %>
              <%= Spree.t(:use_billing_address) %>
            <% end %>
          </p>
          <%= render :partial => 'spree/address/form', :locals => { :form => ship_form, :address_type => 'shipping', :address => @order.ship_address } %>
        </div>
      <% end %>
    </div>
  </div>
</div>

<div class="well text-right form-buttons" data-hook="buttons">
  <%= submit_tag Spree.t(:save_and_continue), :class => 'btn btn-lg btn-success' %>
  <% if try_spree_current_user %>
    <span data-hook="save_user_address">
      &nbsp; &nbsp;
      <%= check_box_tag 'save_user_address', '1', try_spree_current_user.respond_to?(:persist_order_address) %>
      <%= label_tag :save_user_address, Spree.t(:save_my_address) %>
    </span>
  <% end %>
</div>

app/views/spree/checkout/_payment.html.erb
<div class="panel panel-default" id="payment" data-hook>
  <div class="panel-heading">
    <h3 class="panel-title"><%= Spree.t(:payment_information) %></h3>
  </div>
  <div class="panel-body" data-hook="checkout_payment_step">
    <div class="form-group">
      <% if @payment_sources.present? %>
          <table class="existing-credit-card-list" data-hook="existing_cards">
            <tbody>
            <% @payment_sources.each do |card| %>
                <tr id="<%= dom_id(card,'spree')%>" class="<%= cycle('even', 'odd') %>">
                  <td>
                    <%= radio_button_tag "order[existing_card]", card.id, (card == @payment_sources.first), { class: "existing-cc-radio" }  %>
                  </td>
                  <td>
                  <span class="cc-type">
                    <% unless (cc_type = card.cc_type).blank? %>
                      <%= image_tag "credit_cards/icons/#{cc_type}.png" %>
                    <% end %>
                    <% if card.last_digits %>
                      <%= Spree.t(:ending_in) %> <%= card.last_digits %>
                    <% end %>
                  </span> (<span class="full-name"><%= card.name %></span>)
                  </td>
                </tr>
            <% end %>
            </tbody>
          </table>
      <% end %>

      <button id="authorizenet-open-hosted-form" class="btn btn-default">
        <%= Spree.t('authorizenet_hosted_cim.add_new_payment_method') %>
      </button>
    </div>

    <%= render partial: 'spree/checkout/payment/storecredit' %>

    <p class='field' data-hook='coupon_code'>
      <%= form.label :coupon_code %>
      <%= form.text_field :coupon_code, :class => 'form-control' %>
    </p>
  </div>
</div>

<div class="well text-right form-buttons" data-hook="buttons">
  <%= submit_tag Spree.t(:save_and_continue), class: 'btn btn-lg btn-success primary' %>
  <script>Spree.disableSaveOnClick();</script>
</div>

app/views/spree/checkout/payment/_authorizenet_form.html.erb
<form style="display: none" id="authorizenet-hosted-form" method="post" action="<%= form_url %>" target="authorizenet_iframe">
  <input type="hidden" name="token" value="<%= token %>" />
</form>

<div id="authorizenet-hosted-form-modal" class="modal fade" tabindex="-1" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title"><%= Spree.t(:new_payment_method) %></h4>
      </div>
      <div class="modal-body">
        <iframe name="authorizenet_iframe" id="authorizenet_iframe" frameborder="0" scrolling="no" style="width: 435px; height: 925px;"></iframe>
      </div>
    </div>
  </div>
</div>

app/views/spree/shared/_static_address_pane.html.erb
<div class="panel panel-default" id="billing" data-hook>
  <div class="panel-heading">
    <h3 class="panel-title"><%= title %></h3>
  </div>
  <div class="panel-body">
    <table class="table">
      <tbody>
        <tr>
          <th><%= Spree::Address.human_attribute_name(:firstname) %></th>
          <td><%= address.firstname %>
        </tr>
        <tr>
          <th><%= Spree::Address.human_attribute_name(:lastname) %></th>
          <td><%= address.lastname %>
        </tr>
        <tr>
          <th><%= Spree::Address.human_attribute_name(:address1) %></th>
          <td><%= address.address1 %>
        </tr>
        <tr>
          <th><%= Spree::Address.human_attribute_name(:address2) %></th>
          <td><%= address.address2 %>
        </tr>
        <tr>
          <th><%= Spree::Address.human_attribute_name(:city) %></th>
          <td><%= address.city %>
        </tr>
        <tr>
          <th><%= Spree::Address.human_attribute_name(:country) %></th>
          <td><%= address.country.try(:name) %>
        </tr>
        <tr>
          <th><%= Spree::Address.human_attribute_name(:state) %></th>
          <td><%= address.state.try(:name) %>
        </tr>
        <tr>
          <th><%= Spree::Address.human_attribute_name(:zipcode) %></th>
          <td><%= address.zipcode %>
        </tr>
        <tr>
          <th><%= Spree::Address.human_attribute_name(:phone) %></th>
          <td><%= address.phone %>
        </tr>
      </tbody>
    </table>
  </div>
</div>